---
title: "Multiple Regresssion"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


install.packages ("tidyverse")
# olsrr is used for best subsets procedure
install.packages("olsrr")


library(tidyverse)
library(olsrr)

```


```{r}
#turn off scientific notation for all variables so we don't get too many number
options(scipen=999) 

creditdf <- read.csv("Credit.csv")
View(creditdf)


# Step 1: Convert categorical variables to factors with levels and labels
creditdf$Student<-factor(creditdf$Student,levels = c(0,1),labels = c("No","Yes"))
creditdf$Gender<-factor(creditdf$Gender,levels = c(0,1),labels = c("Female","Male"))
creditdf$Married<-factor(creditdf$Married,levels = c(0,1),labels = c("No","Yes"))

#generate summary statistics for all variables in dataframe
summary(creditdf)


                    
# Step 2: Partition the data into a training set and a validation set 
#set seed so the random sample is reproducible
set.seed(42)

# 50%/50% split data into training and validate 
sample <- sample(c(TRUE, FALSE), nrow(creditdf), replace=TRUE, prob=c(0.5,0.5))
traincredit  <- creditdf[sample, ]
validatecredit <- creditdf[!sample, ]



#Step 3: Create a correlation matrix with the quantitative variables in the training dataframe.
cor(creditdf[c(1,2,3,4,5,9)])





#Step 4: Multiple regresssion (MR) with all variables and Balance as outcome.
credit_MRall <- lm(Balance ~ Income + Limit + Rating + Age + Education + Student + Gender + Married, data = traincredit)
summary(credit_MRall)



# Step 5: Run best subsets procedure with multiple regression output 


#Load olsrr library
library(olsrr)

bestsubset <- ols_step_all_possible(credit_MRall)
View(bestsubset)

# Step 6 VIF
vif(credit_MRall)

# Step 7 New MR with training df &Income, Rating, Age, Education,
#Student, Gender, and Married as predictor variables.
credit_MR_withoutLimit <- lm(Balance ~ Income + Rating + Age + Education + Student + Gender + Married, data = traincredit)
summary(credit_MR_withoutLimit) 



#install lm.beta package to extract standardized regression coefficients
install.packages ("lm.beta")

#load lm.beta
library(lm.beta)

#View the multiple regression output
summary(credit_MR_withoutLimit)


# Step 8: Create residual plot and normal prob plot using regression 
# from step 6 credit_MR

#Steps to create a scatter plot of residuals vs. predicted values of the 
#dependent variable

#Create a vector of predicted values generated from the multiple 
#regression above
credit_pred = predict(credit_MR_withoutLimit)

#Create a vector of residuals generated from the multiple regression above
credit_res = resid(credit_MR_withoutLimit)

#Create a data frame of the predicted values and the residuals
pred_res_df <- data.frame(credit_pred, credit_res)

#create a scatterplot of the residuals versus the predicted values
ggplot(data = pred_res_df, mapping = aes(x = credit_pred, y = credit_res)) +
  geom_point() +
  labs(title = "Plot of residuals vs. predicted values", x = "Predicted values",
       y = "Residuals")


#Step 9: Create a Normal Probability Plot 

#create a vector of standardized residuals generated from the multiple
#regression above
credit_std.res = rstandard(credit_MR_withoutLimit)

#produce normal scores for the standardized residuals and create
#normal probability plot
qqnorm(credit_std.res, ylab = "Standardized residuals", xlab = "Normal scores")


# Step 10: Examine output from step 6
summary(credit_MR_withoutLimit)

# Step 11: New MR with training df and statistically significant variables
# significant variables only(income, rating, age, student)


credit_MR_sig <- lm(Balance ~ Income + Rating + Age  + Student, data = traincredit)
summary(credit_MR_sig)


# Step 12: Standardized slope coefficient for Income 
lm.beta(credit_MR_sig)

# Step 13: MR with validation df and stat significant variables
credit_MR_Validate <- lm(Balance ~ Income + Rating + Age  + Student, data = validatecredit)
summary(credit_MR_Validate)





```


```{r}
# Step 14 predict credit card balances
#read inventory dataset into R
inventorydf <- read.csv("credit_card_prediction.csv")
View(inventorydf)

#Convert categorical variables to factors with levels and labels
inventorydf$Student<-factor(inventorydf$Student,levels = c(0,1),labels = c("No","Yes"))

#estimate predicte card balances
predict(credit_MR_Validate, inventorydf, interval = "prediction", level = 0.95)



```

